name: Buld & Publish Snap

on:
  workflow_dispatch:
    inputs:
      EDGEIQ_CODA_VERSION:
        description: 'Version of the snap'
        required: true
      SNAPCRAFT_CHANNELS:
        description: 'Channels for publication (comma-separated)'
        required: false
        default: 'edge,beta,candidate,stable'

jobs:
  build-and-publish:
    name: Build and Publish Snap
    runs-on: ubuntu-latest
    env:
      EDGEIQ_SNAP_NAME: coda
      EDGEIQ_API_URL: https://api.edgeiq.io
      EDGEIQ_CODA_VERSION: ${{ github.event.inputs.EDGEIQ_CODA_VERSION }}
      SNAPCRAFT_CHANNELS: ${{ github.event.inputs.SNAPCRAFT_CHANNELS }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3

      - name: Setup LXD
        run: |
          sudo usermod -aG lxd $USER
          sudo snap install lxd
          sudo lxd init --auto
          newgrp lxd
          sudo chmod 666 /var/snap/lxd/common/lxd/unix.socket

      - name: Build snap
        run: |
          sudo sg lxd -c 'make build'

      - name: Release snap to the specified channels
        run: |
          make publish