#!/usr/bin/env python3

import os
import json
import shutil
import subprocess

print("Starting installation...")
src_conf_dir = os.path.join(os.environ['SNAP'], 'conf')
dst_config_dir = os.path.join(os.environ['SNAP_COMMON'], 'conf')

def set_default_values(data, prefix=''):
    json_data = json.dumps(data)
    print(f"Setting {prefix} to {json_data}")
    subprocess.run(["snapctl", "set", f"{prefix}={json_data}"], check=True)

def load_conf_file(file_name):
    file = os.path.join(src_conf_dir, file_name)
    with open(file, 'r') as f:
        print(f"Loading {file}")
        content = f.read()
        print(content)
        return json.loads(content)

# Copy the default configuration files to the persistent and writable area
print("Copying configuration files...")
shutil.copytree(src_conf_dir, dst_config_dir)

# Set the default values for the snap
print("Setting default values...")
set_default_values(load_conf_file('bootstrap.json'), 'bootstrap')
set_default_values(load_conf_file('conf.json'), 'conf')