#!/usr/bin/env python3

import os
import sys
import logging

sys.path.append(os.path.join(os.environ['SNAP'], 'shared'))

import hook_utils

# Setup logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')

logging.info("Starting refresh...")